use_frameworks!

target 'GMLFoundationExtension_Example' do
  pod 'GMLFoundationExtension', :path => '../'

  target 'GMLFoundationExtension_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
